# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22aede30371bacf232ef6439e703a43f3d8adcfcf9bfe6938d55c8e1801af4f070a80843e82aabce10f15bb4f8c9a58bd6b31b79ad5497794ca134a55ee7df29

test:
  secret_key_base: ab83940f3f90319f9c871f83178b2177be483a112041c767bb84ca8257c8790441a87747cbcf6aa2268a9bb88f0099b62364ea4f542163784352727caa0bbe2a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
